first homework completed
Kimislazuli/java-course-2023-backend-spring pull request #1
Opened 2024-02-18 20:09 UTC by Kimislazuli

* add base logic with dummy repository
* add command menu button

2024-02-19 12:12 UTC, nexen505 requested changes

2024-02-19 12:12 UTC, nexen505 commented on .gitignore
> +/bot/src/main/resources/application-dev.yml
Вопрос: зачем добавлены эти игноры?

2024-02-19 12:12 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/botLogic/Bot.java
> +        return new SetMyCommands(commands.stream().map(command -> new BotCommand(
Косметика: по форматированию некрасиво выглядит - лучше вынести массив в отдельную переменную.

2024-02-19 12:12 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/botLogic/MessageHandler.java
> +    public MessageHandler() {
Вопрос: зачем нужен такой конструктор? Его наполнение вызывает сомнения в его необходимости.

2024-02-19 12:12 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/repository/LinkRepository.java
> +    private final Map<Long, List<Link>> links = new HashMap<>();
Проблема: непотокобезопасная коллекция используется в многопоточной среде веб-сервиса.

Предложение: использовать потокобезопасный тип и изменить логику использования на атомарную.

2024-02-19 12:12 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/repository/UserRepository.java
> +    private final Map<Long, User> users = new HashMap();
Проблема: непотокобезопасная коллекция используется в многопоточной среде веб-сервиса.

Предложение: использовать потокобезопасный тип и изменить логику использования на атомарную.

2024-02-19 12:12 UTC, nexen505 commented on bot/src/test/java/edu/java/bot/LinkActionsTest.java
> +public class LinkActionsTest {
Проблема: тест собирает в себе тесты разных компонентов.

Предложение: декомпозировать тесты на тесты отдельных команд.

2024-02-19 12:12 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/botLogic/MessageHandler.java
> +    @SuppressWarnings("ReturnCount")
Проблема: инспекция не зря подсказывает, что код метода сильно усложнен.

Предложение: разбить его логику на отдельные приватные методы.

2024-02-26 13:45 UTC, nexen505 requested changes

2024-02-26 13:45 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/botLogic/Bot.java
> +    private ApplicationConfig config;
Косметика: можно сделать `final`.

2024-02-26 13:45 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/botLogic/Bot.java
> +    private MessageHandler messageHandler;
Косметика: можно сделать `final`.

2024-02-26 13:45 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/botLogic/Bot.java
> +    private static final Logger LOGGER = LogManager.getLogger(Bot.class);
Проблема: созданный логгер дублирует тот, что создается аннотацией `@Slf4j`.

Предложение: оставить использование одного из них.

2024-02-26 13:45 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/botLogic/Bot.java
> +package edu.java.bot.botLogic;
Проблема: заметил, что именование пакет `botLogic` идет в разрез с Java-спецификацией (https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html).

Предложение: переименовать пакет, чтобы уйти от такого невалидного имени.

2024-02-26 13:45 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/repository/LinkRepository.java
> +        return links.get(userId);
Проблема: возвращаемый список неявно редактируемый.

Предложение: обернуть его в `Collections#unmodifiableList` в случае, если он не `null`.

2024-02-26 13:45 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/repository/LinkRepository.java
> +                links.put(userId, links.get(userId).stream().filter(l -> !l.getUrl().equals(url)).toList());
Проблема: список создается лишний раз за ненадобностью.

Предложение: не сохранять новый список, а удалять элементы из прежнего вызовом `removeIf` без лишнего `contains`.

2024-02-26 13:45 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/repository/LinkRepository.java
> +        if (links.containsKey(userId)) {
Проблема: чтение по ключу происходит в методе несколько раз за ненадобностью.

Предложение: уйти от использования `containsKey` и повторного `get` в пользу единственного чтения посредством `get` и использованием его результата.

2024-02-26 13:45 UTC, nexen505 commented on bot/src/test/java/edu/java/bot/commands_test/ListTest.java
> +public class ListTest {
Косметика: тут и в других тестах можно улучшить именование. Обычно принято именовать `${имя тестируемого класса}Test` (например, для тестирования `ListCommand` создать тест `ListCommandTest`).

2024-02-26 13:45 UTC, nexen505 commented on bot/src/test/java/edu/java/bot/commands_test/ListTest.java
> +package edu.java.bot.commands_test;
Косметика: тесты классов обычно располагают в их же пакете, а не в отдельном, для удобства контроля видимости да и это логично в целом - тесты стоит перенести в пакет команд.

2024-02-26 13:45 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/botLogic/MessageHandler.java
> +        if (user.getState() == State.DEFAULT) {
Косметика: такой ветвящийся `if` можно заменить на использование `switch(user.getState())`.

2024-02-26 13:45 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/botLogic/MessageHandler.java
> +        } else {
Косметика: `else` не нужен.

2024-02-26 13:45 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/botLogic/MessageHandler.java
> +            } else if (messageText.equals(TRACK)) {
Косметика: `else` не нужен.

2024-02-26 17:51 UTC, Kimislazuli commented on bot/src/main/java/edu/java/bot/repository/LinkRepository.java
> +                links.put(userId, links.get(userId).stream().filter(l -> !l.getUrl().equals(url)).toList());
Ну я же возвращаю boolean в зависимости от успешности операции удаления. Если сделать removeIf без проверки включения, статус операции будет некорректно возвращаться. Создание нового списка убрала, это действительнон не очень хорошо.

2024-02-27 14:10 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/repository/LinkRepository.java
> +                links.put(userId, links.get(userId).stream().filter(l -> !l.getUrl().equals(url)).toList());
`removeIf` возвращает boolean, так как нужно, как я понимаю, - можно его использовать.

2024-02-27 14:10 UTC, nexen505 approved these changes

2024-03-01 12:04 UTC, merged