Second homework completed
Kimislazuli/java-course-2023-backend-spring pull request #2
Opened 2024-02-25 17:34 UTC by Kimislazuli

2024-02-29 14:28 UTC, nexen505 requested changes

2024-02-29 14:28 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/client/GithubClient.java
> +        webClient = WebClient.builder().baseUrl(baseUrl).build();
Проблема: тут и в соседнем клиенте при таком создании клиента вручную теряются предконфигурированные фреймворком компоненты.

Предложение: добавить при конфигурации зависимость на WebClient.Builder webClientBuilder и использовать ее для создания клиента.

2024-02-29 14:28 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/sceduler/LinkUpdaterScheduler.java
> +    @Scheduled(fixedDelayString = "#{@schedulerFixedDelay}")
Мысль: можно значительно упростить выражение и избавиться от лишнего бина, если воспользоваться знаком $ для получения конфигурационного свойства приложения по ключу.

2024-02-29 14:28 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/configuration/ClientConfiguration.java
> +        return new GithubClient();
Проблема: не выполнено требование задания по указанию базового адреса и использование значения по умолчанию, если он не указан.

Предложение: воспользоваться при конфигурации свойствами приложения через механизм `@Value`.

2024-02-29 14:28 UTC, nexen505 commented on scrapper/src/test/java/edu/java/scrapper/GithubClientTest.java
> +        stubFor(get(urlEqualTo("/repos/johndoe/java")).willReturn(aResponse()
Проблема: этот стаб специфичен конкретному test-case, но содержится в общей логике.

Предложение: перенести это в имеющийся `@Test`.

2024-02-29 14:28 UTC, nexen505 commented on scrapper/src/test/java/edu/java/scrapper/StackOverflowClientTest.java
> +        server.stubFor(get(urlEqualTo("/questions/7?site=stackoverflow")).willReturn(aResponse()
Проблема: этот стаб специфичен конкретному test-case, но содержится в общей логике.

Предложение: перенести это в имеющийся `@Test`.

2024-03-01 12:32 UTC, Kimislazuli commented on scrapper/src/main/java/edu/java/scrapper/sceduler/LinkUpdaterScheduler.java
> +    @Scheduled(fixedDelayString = "#{@schedulerFixedDelay}")
Да, согласна, изначально и планировала подтягивать напрямую из .yml, но немного смутила строчка в формулировке задания `@Scheduled(fixedDelayString = "#{@beanName}")` , поэтому было решено следовать этому веянию и создать бин, хоть это и излишество своего рода. Вернула получение из файла.

2024-03-01 12:40 UTC, Kimislazuli commented on scrapper/src/main/java/edu/java/scrapper/configuration/ClientConfiguration.java
> +        return new GithubClient();
Немного запугали в чате курса "вредностью" `@Value`, потому что она обеспечивает "слабую связность", так что я думала, что использовать её плохо (хотя контекст очевидно располагает). Хотелось бы разобаться, где находится грань уместного и неуместого использования этой аннотации.

Для решения же пункта задачи подразумевалось использование ссылки в хардкоде конструктора по умолчанию:
```
    public GithubClient() {
        this("https://api.github.com");
    }
```

Исправлено.

Также вопрос, есть ли альтернативы в этой ситуации, что-то кроме аннотации `@Value`?

2024-03-01 15:02 UTC, Kimislazuli commented
Помимо прочего вызывает вопросы, в чем принципиальная разница возвращения Mono и просто упаковываемого в Mono типа...

2024-03-05 12:53 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/sceduler/LinkUpdaterScheduler.java
> +    @Scheduled(fixedDelayString = "#{@schedulerFixedDelay}")
Она нужна для нескольких целей:
- фреймворк через нее понимает тип конфигурируемых свойств,
- предоставление доступа к свойствам в Java через бин-компонент `@ConfigurationProperties`.

2024-03-05 12:55 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/configuration/ClientConfiguration.java
> +        return new GithubClient();
Альтернатива: пользоваться в конфигурации бином-компонентом со свойствами, т.е. `ApplicationConfig`.

2024-03-05 12:57 UTC, nexen505 commented
> Помимо прочего вызывает вопросы, в чем принципиальная разница возвращения Mono и просто упаковываемого в Mono типа...

Принципиальная разница кроется в самом типе, собственно. `Mono` - тип, присущий реактивному программированию и стилю. Он бывает удобен в ситуации, когда весь сервис написан в реактивной парадигме и манипуляция данными происходит реактивно, так что там такие типы естественны.

2024-03-05 13:01 UTC, nexen505 approved these changes

2024-03-07 18:37 UTC, merged