Hw5
Kimislazuli/java-course-2023-backend-spring pull request #6
Opened 2024-03-17 16:19 UTC by Kimislazuli

Отразила непонятные вещи в конкретных местах кода комментариями.

+ кажется не совсем корректной логика сервиса с многократным выходом в базу данных, возможно, стоит ожидать от нее ответ с ошибкой, а не перестраховываться проверками наличия.

Выяснилось, что не ловит ошибки ExceptionHandler, что с этим делать, пока не поняла.

2024-03-21 14:54 UTC, Kimislazuli commented
Я сломала чеки в пре мерджем с 3 домашкой и случайным залитием вместе с мерджем интеграции двух микросервисов (1 задача 6 дз). 
Доделаю эту задачу и залью в эту ветку, все починиться должно. :(

2024-03-22 17:04 UTC, Kimislazuli commented
Сделала интеграцию микросервисов и починила тем самым билд. Задача вроде готова к проверке.

2024-03-28 12:57 UTC, nexen505 requested changes

2024-03-28 12:57 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/domain/dao/jdbc/JdbcChatDao.java
> +    // Пока метод добавления возвращает по факту свой же параметр (чтобы формировать с
Мысль: мне кажется, в данном случае это нормально. Сигнатура метода удобная, так как если понадобится ввести суррогатный первичный ключ, то сигнатура позволяет его вернуть.

2024-03-28 12:57 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/domain/dao/jdbc/JdbcChatDao.java
> +    // + так и не поняла, какой эксепшн ловить при повторной попытке выполнить операцию.
Обычно в таких случаях есть `org.springframework.dao.DuplicateKeyException`.

2024-03-28 12:57 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/domain/dao/jdbc/JdbcChatDao.java
> +    // нужно ли это вообще делать или на уровне запроса решать проблему?
Это нужно определять логикой твоего контракта, должен ли твой метод бросать ошибку при нарушении уникальности.

2024-03-28 12:57 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/domain/dao/jdbc/JdbcChatToLinkConnectionDao.java
> +    // здесь аналогичная проблема: нет никакого айди, который можно было бы вернуть, в итоге
В данном случае как раз удобнее вернуть какой-то объект-обертку над парой значений. Тут это, думаю, будет `ChatToLinkConnection`.

2024-03-28 12:57 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/service/jdbc_impl/JdbcLinkService.java
> +        long chatCount = chatDao.findAll()
Проблема: тут и в других методах рядом читать всю БД в память, чтобы найти айдишник, чересчур :)

Предложение: фильтровать на уровне запросов в БД, а не в памяти.

2024-03-28 12:57 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/service/jdbc_impl/JdbcLinkService.java
> +    public Link add(long tgChatId, URI url) throws AlreadyExistException, RepeatedRegistrationException {
Предложение: согласен с мыслью в комментарии, что в целом внешние методы логические много ходят в БД. Если хочется сделать user-friendly, то можно добавлять сущности в БД с игнором конфликта на уровне БД `insert into ... on conflict do nothing`.

2024-03-28 12:58 UTC, nexen505 commented
> Отразила непонятные мне вещи в конкретных местах кода комментариями.
> 
> Отдельно здесь от себя замечу:
> 
>     * кажется не совсем корректной логика сервиса с многократным выходом в базу данных: невыгодно по ресурсам и не очень работает в условиях многопоточки, как я понимаю. Возможно, стоит ожидать от нее ответ с ошибкой, а не перестраховываться проверками наличия. Как сделать лучше?
> 
>     * выяснилось, что не ловит ошибки ExceptionHandler, что с этим делать, пока не поняла.
>       upd: все ок с обработчиками.

Постарался во всех найденных местах ответить. Концептуально подсвечу, что подобные конфликты лучше разруливать на уровне БД и максимизировать ее использование в целом (много где в коде сейчас происходит логика на уровне кода с большим числом запросов). Попробуй еще раз свежим взглядом с учетом мыслей пересмотреть реализации и на очередной итерации проверки подсветить проблемные места.

2024-04-02 14:50 UTC, Kimislazuli commented
В целом попыталась в соответствии с замечением поправить взаимодействие с бд, действительно не очень хорошими вышли методы выгрузки всей базы, заменила обычными селектами.
Однако проблема с тем, что сервисы делают многочисленные проверки наличия перед добавлением связанных сущностей остались (в частности касается добавления ссылки и её привязки к чату), то есть я делаю для "родительских" сущностей несколько запросов к бд с целью проверки наличия и только потом добавляю связь. Это не слишком частое обращение к базе?

2024-04-08 07:04 UTC, nexen505 commented
> В целом попыталась в соответствии с замечением поправить взаимодействие с бд, действительно не очень хорошими вышли методы выгрузки всей базы, заменила обычными селектами. Однако проблема с тем, что сервисы делают многочисленные проверки наличия перед добавлением связанных сущностей остались (в частности касается добавления ссылки и её привязки к чату), то есть я делаю для "родительских" сущностей несколько запросов к бд с целью проверки наличия и только потом добавляю связь. Это не слишком частое обращение к базе?

Зависит от проверки наличия. Например, внешние ключи на уровне БД и так проверяются при вставке. То есть нет смысла проверять наличие связанной сущности при добавлении связи, так как связь и так не добавится для тех, кого нельзя связать.

2024-04-08 07:05 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/domain/dao/jdbc/JdbcChatDao.java
> +        return rowsAffected == 1 ? Optional.of(chatId) : Optional.empty();
Вопрос: есть ли тест на то, что тут возвращается существующий индекс при конфликте добавления?

2024-04-09 09:47 UTC, Kimislazuli commented on scrapper/src/main/java/edu/java/scrapper/domain/dao/jdbc/JdbcChatDao.java
> +        return rowsAffected == 1 ? Optional.of(chatId) : Optional.empty();
нет... нужно изменить код и добавить.

2024-04-09 09:59 UTC, Kimislazuli commented on scrapper/src/main/java/edu/java/scrapper/domain/dao/jdbc/JdbcChatDao.java
> +        return rowsAffected == 1 ? Optional.of(chatId) : Optional.empty();
Вообще я думала, что возвращаю пустой optional, чтобы сигнализировать о некорректном вызове метода (вместо того, чтобы кидать исключение). Создается впечатление, что повторное добавление тогда тоже нормальное поведение, но как достать ключ без лишнего селекта -- я не знаю (кейхолдер не спасёт вроде бы), а ходить в базу лишний раз не хочется. Получается, всегда возвращать параметр метода вне зависимости от результата исполнения запроса к бд?

2024-04-09 12:22 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/domain/dao/jdbc/JdbcChatDao.java
> +        return rowsAffected == 1 ? Optional.of(chatId) : Optional.empty();
Насколько вижу по коду проекта, результат операции никак не используется, - метод выглядит логично назвать типа `createIfNotExist` или что-то в таком духе.

2024-04-10 13:02 UTC, nexen505 requested changes

2024-04-10 13:02 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/service/jdbc_impl/JdbcLinkService.java
> +    public Collection<Link> listAll(long tgChatId) {
Проблема: запрос достает все чаты и фильтрует в памяти и делает запрос на каждый чат, что дает очень большое количество запросов к БД.

Предложение: реализовать в `JdbcLinkDao` получение ссылок чата одним запросом к БД через джоин `link` к `chat_to_link_connection` и фильтрацию по идентификатору чата.

2024-04-10 13:02 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/service/jdbc_impl/JdbcLinkService.java
> +public class JdbcLinkService implements LinkService {
Проблема: методы сервиса не атомарны в применении изменений.

Предложение: использовать `@Transactional`.

2024-04-10 13:02 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/service/jdbc_impl/JdbcTgChatService.java
> +public class JdbcTgChatService implements TgChatService {
Проблема: методы сервиса не атомарны в применении изменений.

Предложение: использовать `@Transactional`.

2024-04-10 13:03 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/domain/dao/jdbc/JdbcChatDao.java
> +    public Optional<Long> createIfNotExist(long chatId) {
Мысль: думаю, тут вообще не нужен `Optional`, так как всегда будет возвращаемое значение.

2024-04-10 13:04 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/domain/dao/jdbc/JdbcChatToLinkConnectionDao.java
> +    public Optional<ChatToLinkConnection> createIfNotExist(long chatId, long linkId) {
Мысль: думаю, тут вообще не нужен Optional, так как всегда будет возвращаемое значение.

2024-04-10 13:04 UTC, nexen505 commented
Еще надо бы тестов побольше добавить, особенно для сервисов.

2024-04-12 14:27 UTC, Kimislazuli commented on scrapper/src/main/java/edu/java/scrapper/domain/dao/jdbc/JdbcChatDao.java
> +    public Optional<Long> createIfNotExist(long chatId) {
Я возвращаю пустой Optional, если чат уже существует. Не нужно?

2024-04-12 14:28 UTC, Kimislazuli commented
Да, действительно есть проблемы с тем, чтобы понимать, что нужно тестировать. Про сервисы я вообще как-то забыла в этот раз... А в следующем дз они почему-то протестированы уже.

2024-04-15 05:36 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/domain/dao/jdbc/JdbcChatDao.java
> +    public Optional<Long> createIfNotExist(long chatId) {
В этом нет смысла, на мой взгляд.

2024-04-15 05:37 UTC, nexen505 approved these changes

2024-04-19 11:20 UTC, merged